### PR TITLE
fix handling of 'image' parameter

### PR DESCRIPTION
**Pull request by yamaryoxxxx**
seems to be a trivial bug.

### CODE REVIEW

**Comment by jpmonette** [comment]
@yamaryoxxxx Thanks for your time.

This can cause an issue with `.jpg` file format (as an example) since the correct mime-type is `image/jpeg` and not `image/jpg`. I believe using a library such as https://www.npmjs.com/package/mime-types would be a bit more solid.

I would be open to merge if you provide as a source the need supporting that change + if it uses the library above or another solid library.

**Comment by yamaryoxxxx** [comment]
> I would be open to merge if you provide as a source the need supporting that change
I think #33 seems to be an example.

**Comment by jpmonette** [comment]
@yamaryoxxxx I'm curious about what has been changed in the package.json? I tried to revert the changes since this file is outside the scope of that change. Can you exclude it from the PR or create another PR with only the test file, updated feed.js and the compiled JS files?

Thanks.

**Comment by jpmonette** [comment]
Considering the impact on multiple unrelated files and no fix, will close this PR.

**Pull request closed without merging**
